//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicoVehicle.DAL.ResourceFiles {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompanyDALResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompanyDALResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("UnicoVehicle.DAL.ResourceFiles.CompanyDALResources", typeof(CompanyDALResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string GetCompany {
            get {
                return ResourceManager.GetString("GetCompany", resourceCulture);
            }
        }
        
        internal static string GetCompanybyId {
            get {
                return ResourceManager.GetString("GetCompanybyId", resourceCulture);
            }
        }
        
        internal static string InsertCompany {
            get {
                return ResourceManager.GetString("InsertCompany", resourceCulture);
            }
        }
        
        internal static string DeleteCompany {
            get {
                return ResourceManager.GetString("DeleteCompany", resourceCulture);
            }
        }
        
        internal static string UpdateCompany {
            get {
                return ResourceManager.GetString("UpdateCompany", resourceCulture);
            }
        }
        
        internal static string GetCompanyCountry {
            get {
                return ResourceManager.GetString("GetCompanyCountry", resourceCulture);
            }
        }
        
        internal static string GetCompanyCountrybyId {
            get {
                return ResourceManager.GetString("GetCompanyCountrybyId", resourceCulture);
            }
        }
        
        internal static string InsertCompanyCountry {
            get {
                return ResourceManager.GetString("InsertCompanyCountry", resourceCulture);
            }
        }
        
        internal static string DeleteCompanyCountry {
            get {
                return ResourceManager.GetString("DeleteCompanyCountry", resourceCulture);
            }
        }
        
        internal static string UpdateCompanyCountry {
            get {
                return ResourceManager.GetString("UpdateCompanyCountry", resourceCulture);
            }
        }
        
        internal static string GetShowroom {
            get {
                return ResourceManager.GetString("GetShowroom", resourceCulture);
            }
        }
        
        internal static string GetShowroombyId {
            get {
                return ResourceManager.GetString("GetShowroombyId", resourceCulture);
            }
        }
        
        internal static string InsertShowroom {
            get {
                return ResourceManager.GetString("InsertShowroom", resourceCulture);
            }
        }
        
        internal static string DeleteShowroom {
            get {
                return ResourceManager.GetString("DeleteShowroom", resourceCulture);
            }
        }
        
        internal static string UpdateShowroom {
            get {
                return ResourceManager.GetString("UpdateShowroom", resourceCulture);
            }
        }
    }
}
