//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicoVehicle.DAL.ResourceFiles {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MasterDALResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MasterDALResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("UnicoVehicle.DAL.ResourceFiles.MasterDALResources", typeof(MasterDALResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string GetAccessoriesType {
            get {
                return ResourceManager.GetString("GetAccessoriesType", resourceCulture);
            }
        }
        
        internal static string GetAccessoriesTypebyId {
            get {
                return ResourceManager.GetString("GetAccessoriesTypebyId", resourceCulture);
            }
        }
        
        internal static string InsertAccessoriesType {
            get {
                return ResourceManager.GetString("InsertAccessoriesType", resourceCulture);
            }
        }
        
        internal static string DeleteAccessoriesType {
            get {
                return ResourceManager.GetString("DeleteAccessoriesType", resourceCulture);
            }
        }
        
        internal static string UpdateAccessoriesType {
            get {
                return ResourceManager.GetString("UpdateAccessoriesType", resourceCulture);
            }
        }
        
        internal static string GetFuelType {
            get {
                return ResourceManager.GetString("GetFuelType", resourceCulture);
            }
        }
        
        internal static string GetFuelTypebyId {
            get {
                return ResourceManager.GetString("GetFuelTypebyId", resourceCulture);
            }
        }
        
        internal static string InsertFuelType {
            get {
                return ResourceManager.GetString("InsertFuelType", resourceCulture);
            }
        }
        
        internal static string DeleteFuelType {
            get {
                return ResourceManager.GetString("DeleteFuelType", resourceCulture);
            }
        }
        
        internal static string GetVehicleType {
            get {
                return ResourceManager.GetString("GetVehicleType", resourceCulture);
            }
        }
        
        internal static string GetVehicleTypebyId {
            get {
                return ResourceManager.GetString("GetVehicleTypebyId", resourceCulture);
            }
        }
        
        internal static string InsertVehicleType {
            get {
                return ResourceManager.GetString("InsertVehicleType", resourceCulture);
            }
        }
        
        internal static string DeleteVehicleType {
            get {
                return ResourceManager.GetString("DeleteVehicleType", resourceCulture);
            }
        }
        
        internal static string GetUserType {
            get {
                return ResourceManager.GetString("GetUserType", resourceCulture);
            }
        }
        
        internal static string GetUserTypebyId {
            get {
                return ResourceManager.GetString("GetUserTypebyId", resourceCulture);
            }
        }
        
        internal static string InsertUserType {
            get {
                return ResourceManager.GetString("InsertUserType", resourceCulture);
            }
        }
        
        internal static string DeleteUserType {
            get {
                return ResourceManager.GetString("DeleteUserType", resourceCulture);
            }
        }
        
        internal static string GetTransmissionType {
            get {
                return ResourceManager.GetString("GetTransmissionType", resourceCulture);
            }
        }
        
        internal static string GetTransmissionTypebyId {
            get {
                return ResourceManager.GetString("GetTransmissionTypebyId", resourceCulture);
            }
        }
        
        internal static string InsertTransmissionType {
            get {
                return ResourceManager.GetString("InsertTransmissionType", resourceCulture);
            }
        }
        
        internal static string DeleteTransmissionType {
            get {
                return ResourceManager.GetString("DeleteTransmissionType", resourceCulture);
            }
        }
    }
}
