//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicoVehicle.DAL.ResourceFiles {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MescellaneousResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MescellaneousResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("UnicoVehicle.DAL.ResourceFiles.MescellaneousResources", typeof(MescellaneousResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string GetDistrictbyId {
            get {
                return ResourceManager.GetString("GetDistrictbyId", resourceCulture);
            }
        }
        
        internal static string GetCompanybyId {
            get {
                return ResourceManager.GetString("GetCompanybyId", resourceCulture);
            }
        }
        
        internal static string GetInsuranceCompanybyId {
            get {
                return ResourceManager.GetString("GetInsuranceCompanybyId", resourceCulture);
            }
        }
        
        internal static string GetStatebyId {
            get {
                return ResourceManager.GetString("GetStatebyId", resourceCulture);
            }
        }
        
        internal static string GetShowroombyId {
            get {
                return ResourceManager.GetString("GetShowroombyId", resourceCulture);
            }
        }
        
        internal static string GetVehiclebyId {
            get {
                return ResourceManager.GetString("GetVehiclebyId", resourceCulture);
            }
        }
    }
}
