//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicoVehicle.DAL.ResourceFiles {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrderDALResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderDALResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("UnicoVehicle.DAL.ResourceFiles.OrderDALResources", typeof(OrderDALResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string GetOrderbyShowroom {
            get {
                return ResourceManager.GetString("GetOrderbyShowroom", resourceCulture);
            }
        }
        
        internal static string GetOrderbyShowroomandVehicle {
            get {
                return ResourceManager.GetString("GetOrderbyShowroomandVehicle", resourceCulture);
            }
        }
        
        internal static string GetOrderbyCustomer {
            get {
                return ResourceManager.GetString("GetOrderbyCustomer", resourceCulture);
            }
        }
        
        internal static string GetOrderbyId {
            get {
                return ResourceManager.GetString("GetOrderbyId", resourceCulture);
            }
        }
        
        internal static string GetOrderbyShowroomCustomer {
            get {
                return ResourceManager.GetString("GetOrderbyShowroomCustomer", resourceCulture);
            }
        }
        
        internal static string InsertOrder {
            get {
                return ResourceManager.GetString("InsertOrder", resourceCulture);
            }
        }
        
        internal static string UpdateOrder {
            get {
                return ResourceManager.GetString("UpdateOrder", resourceCulture);
            }
        }
        
        internal static string UpdateOrderStatus {
            get {
                return ResourceManager.GetString("UpdateOrderStatus", resourceCulture);
            }
        }
        
        internal static string GetmaxOrderId {
            get {
                return ResourceManager.GetString("GetmaxOrderId", resourceCulture);
            }
        }
        
        internal static string GetPostBuyingDetailbyId {
            get {
                return ResourceManager.GetString("GetPostBuyingDetailbyId", resourceCulture);
            }
        }
        
        internal static string InsertPostBuyingDetail {
            get {
                return ResourceManager.GetString("InsertPostBuyingDetail", resourceCulture);
            }
        }
        
        internal static string UpdatePostBuyingDetail {
            get {
                return ResourceManager.GetString("UpdatePostBuyingDetail", resourceCulture);
            }
        }
    }
}
