//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicoVehicle.DAL.ResourceFiles {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VehicleDALResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VehicleDALResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("UnicoVehicle.DAL.ResourceFiles.VehicleDALResources", typeof(VehicleDALResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string GetAccessories {
            get {
                return ResourceManager.GetString("GetAccessories", resourceCulture);
            }
        }
        
        internal static string GetAccessorybyId {
            get {
                return ResourceManager.GetString("GetAccessorybyId", resourceCulture);
            }
        }
        
        internal static string InsertAccessory {
            get {
                return ResourceManager.GetString("InsertAccessory", resourceCulture);
            }
        }
        
        internal static string DeleteAccessory {
            get {
                return ResourceManager.GetString("DeleteAccessory", resourceCulture);
            }
        }
        
        internal static string UpdateAccessory {
            get {
                return ResourceManager.GetString("UpdateAccessory", resourceCulture);
            }
        }
        
        internal static string GetVehicleName {
            get {
                return ResourceManager.GetString("GetVehicleName", resourceCulture);
            }
        }
        
        internal static string GetVehicleNamebyId {
            get {
                return ResourceManager.GetString("GetVehicleNamebyId", resourceCulture);
            }
        }
        
        internal static string InsertVehicleName {
            get {
                return ResourceManager.GetString("InsertVehicleName", resourceCulture);
            }
        }
        
        internal static string DeleteVehicleName {
            get {
                return ResourceManager.GetString("DeleteVehicleName", resourceCulture);
            }
        }
        
        internal static string UpdateVehicleName {
            get {
                return ResourceManager.GetString("UpdateVehicleName", resourceCulture);
            }
        }
        
        internal static string GetVehiclebyTransmission {
            get {
                return ResourceManager.GetString("GetVehiclebyTransmission", resourceCulture);
            }
        }
        
        internal static string GetVehiclebyFuel {
            get {
                return ResourceManager.GetString("GetVehiclebyFuel", resourceCulture);
            }
        }
        
        internal static string GetVehiclebyVehicleType {
            get {
                return ResourceManager.GetString("GetVehiclebyVehicleType", resourceCulture);
            }
        }
        
        internal static string GetVehiclebyVariant {
            get {
                return ResourceManager.GetString("GetVehiclebyVariant", resourceCulture);
            }
        }
        
        internal static string GetVehiclebyName {
            get {
                return ResourceManager.GetString("GetVehiclebyName", resourceCulture);
            }
        }
        
        internal static string GetVehiclebyId {
            get {
                return ResourceManager.GetString("GetVehiclebyId", resourceCulture);
            }
        }
        
        internal static string InsertVehicle {
            get {
                return ResourceManager.GetString("InsertVehicle", resourceCulture);
            }
        }
        
        internal static string DeleteVehicle {
            get {
                return ResourceManager.GetString("DeleteVehicle", resourceCulture);
            }
        }
        
        internal static string UpdateVehicle {
            get {
                return ResourceManager.GetString("UpdateVehicle", resourceCulture);
            }
        }
        
        internal static string GetVehicleVariantbyCompany {
            get {
                return ResourceManager.GetString("GetVehicleVariantbyCompany", resourceCulture);
            }
        }
        
        internal static string GetVehicleVariantbyId {
            get {
                return ResourceManager.GetString("GetVehicleVariantbyId", resourceCulture);
            }
        }
        
        internal static string InsertVehicleVariant {
            get {
                return ResourceManager.GetString("InsertVehicleVariant", resourceCulture);
            }
        }
        
        internal static string DeleteVehicleVariant {
            get {
                return ResourceManager.GetString("DeleteVehicleVariant", resourceCulture);
            }
        }
    }
}
