//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicoVehicle.DAL {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DALResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DALResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("UnicoVehicle.DAL.DALResources", typeof(DALResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string GetCountry {
            get {
                return ResourceManager.GetString("GetCountry", resourceCulture);
            }
        }
        
        internal static string InsertCountry {
            get {
                return ResourceManager.GetString("InsertCountry", resourceCulture);
            }
        }
        
        internal static string GetCountrybyId {
            get {
                return ResourceManager.GetString("GetCountrybyId", resourceCulture);
            }
        }
        
        internal static string DeleteCountry {
            get {
                return ResourceManager.GetString("DeleteCountry", resourceCulture);
            }
        }
        
        internal static string GetState {
            get {
                return ResourceManager.GetString("GetState", resourceCulture);
            }
        }
        
        internal static string InsertState {
            get {
                return ResourceManager.GetString("InsertState", resourceCulture);
            }
        }
        
        internal static string GetStatebyId {
            get {
                return ResourceManager.GetString("GetStatebyId", resourceCulture);
            }
        }
        
        internal static string DeleteState {
            get {
                return ResourceManager.GetString("DeleteState", resourceCulture);
            }
        }
    }
}
